remote_theme: pages-themes/minimal@v0.2.0
title: CHEEREIO
description: Free software for emission quantification
logo: /assets/transparent_cheereio_logo.png
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
